# imports
from six.moves import xrange

# variables
# DEFAULT_STOCKS_PATH = 'all_stocks_5yr.csv'
DEFAULT_DATA_PATH = 'nasdaq.csv'
DEFAULT_DATA_SET_PATH = 'data_set.pkl'
DEFAULT_TENSORBOARD_PATH = 'tensorboard'
DEFAULT_CHECKPOINTS_PATH = 'checkpoints'

DEFAULT_N_DAYS_PER_DATAPOINT = 1
DEFAULT_OVER_PERCENTAGE = 1.01
DEFAULT_UNDER_PERCENTAGE = 0.99 
DEFAULT_INPUT_N_DATAPOINTS = 20
DEFAULT_TEST_DATA_PERCENTAGE = 0.02

DEFAULT_BATCH_SIZE = 64
DEFAULT_LEARNING_RATE = 8e-3
DEFAULT_LEARNING_RATE_DECAY_FACTOR = 0.98
DEFAULT_RNN_LAYER_SIZE = 128
DEFAULT_N_RNN_LAYERS = 5
DEFAULT_FCN_LAYER_SIZE = 128
DEFAULT_N_FCN_LAYERS = 3
DEFAULT_DROPOUT = 0.5

DEFAULT_SAVE_STEP_INTERVAL = 10000
DEFAULT_BREAK_STEP_INTERVAL = 1000
DEFAULT_N_BATCHES_TO_ACCURACY_EVAL = 50
